### PR TITLE
add a contact page

### LINKED ISSUE #30: contact page link is broken
should have some way to get in touch with us? maybe just send us an email through a web form?

### PR DESCRIPTION
**Pull request by igor47**
describes a few ways to get in contact, plus all the things we need
help with. holy shit, it's a long list.

we should probably talk about how people should be able to get in touch.
is it time for a slack?

closes #30

### CODE REVIEW

**Comment by davideg** [comment]
I think it could be useful to think about "Contact Us" from the perspective of a user/captain having a question about Spaceship Earth vs a potential contributor looking to help us out in the development of this tool.

Email and Reddit seem geared towards the end users.
GitHub is obviously geared towards contributors.

If we were to introduce something like Slack I'm guessing this would be for contributors rather than users, right? I get that all we have is contributors as the moment but I think keeping this distinction clear will be helpful when thinking about what types of communication we want to foster.

Edit: for now we should certainly ship something like this to start soliciting the type of help we need

**Comment by davideg** [comment]
I hope you don't mind me changing your language to be a little less self-deprecating. I think we can still be humble and authentic and focus on a message that inspires confidence 😉

**Review by davideg — APPROVED** [review]
I changed the language a bit to focus less on how little we know what we're doing and more on what we're inviting in :wink:

**Comment by igor47** [comment]
thanks for the fixes, david! feel free to merge and ship, or i'll do it when i get home.

**Comment by svetlichnaya** [comment]
I support the original intention & love the tone improvements! And realizing we need to think about processes :)

**Comment by davideg** [comment]
@igor47 I've obviously merged the changes but I'll let you ship it to production. I'm about to head out and don't want to break anything :grin:

**Pull request merged**
